apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
  labels:
    app-type: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  sources:
    - repoURL: "https://github.com/aferentech/assignment.git"
      path: argocd/apps
      targetRevision: main
      directory:
        recurse: true
  project: argocd-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
