apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secrets-store-gcp-provider
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchExpressions:
            - { key: env, operator: Exists }
  template:
    metadata:
      name: "secrets-store-gcp-provider-{{.metadata.labels.env}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/GoogleCloudPlatform/secrets-store-csi-driver-provider-gcp.git
        targetRevision: main
        path: deploy
      destination:
        server: "{{.server}}"
        namespace: kube-system
      syncPolicy:
        automated:
          prune: true
          selfHeal: true