{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    kubernetes.io/ingress.class: "gce"
    networking.gke.io/managed-certificates: {{ .Values.serviceAccount.name }}-cert
    {{- if .Values.ingress.staticIpName }}
    kubernetes.io/ingress.global-static-ip-name: {{ .Values.ingress.staticIpName }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.serviceAccount.name }}
                port:
                  number: {{ .Values.service.port }}
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.serviceAccount.name }}-cert
spec:
  domains:
    - {{ .Values.ingress.host }}
{{- end }}
