apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.serviceAccount.name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
